LEXICON_RU: dict[str, str] = {
    "start": "👋 Добро пожаловать в чат-бот поддержки!\n\n"
            "Я помогу вам найти ответы на ваши вопросы. Вы можете:\n"
            "• Задать свой вопрос, написав его в чате\n"
            "• Посмотреть историю ваших вопросов\n"
            "• Изучить часто задаваемые вопросы\n"
            "• Обратиться в поддержку для связи с оператором\n\n"
            "После получения ответа вы можете оценить его качество, "
            "поставив реакцию 👍 или 👎",
    "main_menu": "Главное меню",
    "history": "📜 История вопросов",
    "faq": "🔍 Часто задаваемые вопросы",
    "support": "🛠 Поддержка",
    "close": "❌ Выйти",
    "close_support": "❌ Выйти из чата",
    "support_message": "Оператор подключился к чату. Задавайте ваши вопросы.",
    "support_message_close": "Чат поддержки закрыт оператором.",
    "support_message_no_chat": "У вас нет активного чата.",
    "support_message_already_chat": "У вас есть активный чат",
    "support_message_you_close_chat": "Вы закрыли чат.",
    "support_message_close_chat_admin": "✅ Чат с пользователем завершен",
    "support_message_close_chat_user": "✅ Чат с оператором завершен",
    "support_message_cant_take_chat": "Чат уже взят другим оператором или закрыт.",
    "support_message_you_take_chat": "Вы подключились к чату с пользователем",
    "support_message_operator_take_chat": "Оператор подключился к чату. Задавайте ваши вопросы.",
    "support_message_operator": "Оператор",
    "support_message_user": "Пользователь",
    "support_message_answer_get_error": "Произошла ошибка при получении ответа. Попробуйте позже.",
    "support_message_answer_error_processing": "Произошла ошибка при обработке вашего вопроса. Пожалуйста, попробуйте еще раз.",
    "support_message_you_have_chat": "У вас уже открыт чат поддержки. Ожидайте оператора.",
    "support_message_you_are_admin": "Вы являетесь администратором.",
    "support_message_request_sent": "Запрос в службу поддержки отправлен. Ожидайте оператора.",
    "support_message_user_request": "Пользователь запрашивает поддержку.",
}
LEXICON_EN: dict[str, str] = {
    "start": "👋 Welcome to the Chat Bot support!\n\nI will help you find answers to your questions. You can:\n• Ask your question by writing it in the chat\n• View the history of your questions\n• study frequently asked questions\n• Contact support for communication with the operator\n\nAfter receiving an answer, you can evaluate its quality by setting the reaction # or 👎",
    "main_menu": "The main menu",
    "history": "📜 History of questions",
    "faq": "🔍 frequently asked questions",
    "support": "🛠 support",
    "close": "❌ Exit",
    "close_support": "❌ get out of the chat",
    "support_message": "The operator connected to the chat. Ask your questions.",
    "support_message_close": "The support chat is closed by the operator.",
    "support_message_no_chat": "You have no active chat.",
    "support_message_already_chat": "You have an active chat",
    "support_message_you_close_chat": "You closed the chat.",
    "support_message_close_chat_admin": "✅ Chat with the user is completed",
    "support_message_close_chat_user": "✅ Chat with the operator completed",
    "support_message_cant_take_chat": "The chat has already been taken by another operator or closed.",
    "support_message_you_take_chat": "You connected to a chat with the user",
    "support_message_operator_take_chat": "The operator connected to the chat. Ask your questions.",
    "support_message_operator": "Operator",
    "support_message_user": "User",
    "support_message_answer_get_error": "There was an error when receiving an answer. Try it later.",
    "support_message_answer_error_processing": "There was an error when processing your question. Please try again.",
    "support_message_you_have_chat": "You have already opened support chat. Expect the operator.",
    "support_message_you_are_admin": "You are an administrator.",
    "support_message_request_sent": "A request to the support service was sent. Expect the operator.",
    "support_message_user_request": "The user requests support."
}
LEXICON_CN: dict[str, str] = {
    "start": "👋欢迎来到聊天机器人支持！\n\n我会帮助您找到问题的答案。你可以：\n•通过在聊天中写下问题来询问您的问题\n•查看问题的历史\n•学习常见问题\n•与操作员进行沟通的联系支持\n\n收到答案后，您可以通过设置反应＃或👎来评估其质量",
    "main_menu": "主菜单",
    "history": "📜问题的历史",
    "faq": "🔍经常问问题",
    "support": "🛠支持",
    "close": "❌退出",
    "close_support": "❌离开聊天",
    "support_message": "操作员连接到聊天。问你的问题。",
    "support_message_close": "支持聊天由操作员关闭。",
    "support_message_no_chat": "您没有积极的聊天。",
    "support_message_already_chat": "你有一个积极的聊天",
    "support_message_you_close_chat": "您关闭了聊天。",
    "support_message_close_chat_admin": "✅与用户聊天",
    "support_message_close_chat_user": "✅与完成的操作员聊天",
    "support_message_cant_take_chat": "聊天已经由另一个操作员进行或关闭。",
    "support_message_you_take_chat": "您连接到与用户聊天",
    "support_message_operator_take_chat": "操作员连接到聊天。问你的问题。",
    "support_message_operator": "操作员",
    "support_message_user": "用户",
    "support_message_answer_get_error": "收到答案时存在错误。稍后再尝试。",
    "support_message_answer_error_processing": "处理您的问题时存在错误。请重试。",
    "support_message_you_have_chat": "您已经打开了支持聊天。期望操作员。",
    "support_message_you_are_admin": "您是管理员。",
    "support_message_request_sent": "向支持服务的请求发送了。期望操作员。",
    "support_message_user_request": "用户请求支持。"
}
